blank_issues_enabled: false
contact_links:
  - name: Do you need help?
    url: https://v2.hardhat.org/hardhat-runner/docs/guides/getting-help
    about: Check our guide on how to get help with Hardhat
