name: Cache

on:
  push:
    branches:
      - main
      - pre-release-testing-branch
      - changeset-release/main
      - v2
    paths:
      - ".github/workflows/cache.yml"
      - "**/pnpm-lock.yaml"
  pull_request:
    paths:
      - ".github/workflows/cache.yml"
      - "**/pnpm-lock.yaml"
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  cache:
    name: Cache
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v4
      - id: env
        uses: ./.github/actions/setup-env
        with:
          cache-save: true
      - name: Install
        if: steps.env.outputs.cache-hit != 'true'
        run: |
          for lockfile in $(find "$(pwd)" -name pnpm-lock.yaml); do
            pushd "$(dirname "$lockfile")"
              pnpm install --frozen-lockfile --prefer-offline
            popd
          done
