name: Run the Hardhat 3 test suite with the latest dependency versions

on:
  schedule:
    - cron: "0 0/8 * * *"
  workflow_dispatch:

jobs:
  test-without-pnpm-lock-yaml:
    name: Test without pnpm-lock.yaml
    strategy:
      matrix:
        system: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-env
      - name: Delete pnpm-lock.yaml
        run: "rm pnpm-lock.yaml"
      - name: Install
        run: pnpm install --no-frozen-lockfile
      - name: List dependencies
        run: pnpm list -r --depth 2
      - name: Run build
        # Ensure all projects are built before parallel test execution
        run: pnpm build
      - name: Run tests
        run: pnpm test || (echo "===== Retry =====" && pnpm test)
        env:
          # temporary fix, see https://github.com/mochajs/mocha/issues/5452
          NODE_OPTIONS: "--no-experimental-strip-types"
      - name: Notify failures
        if: failure()
        uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
        with:
          payload: |
            {
              "workflow_name": "${{ github.workflow }}",
              "run_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.GH_ACTION_NOTIFICATIONS_SLACK_WEBHOOK_URL }}
