# name: Check Docs Site

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - ".github/workflows/check-docs-site.yml"
#       - "docs/**"
#       - "packages/**"
#   pull_request:
#     paths:
#       - ".github/workflows/check-docs-site.yml"
#       - "docs/**"
#       - "packages/**"
#   workflow_dispatch:

# concurrency:
#   group: ${{github.workflow}}-${{github.ref}}
#   cancel-in-progress: true

# jobs:
#   build:
#     name: Build Docs
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: ./.github/actions/setup-env
#       - name: Install
#         run: pnpm install --frozen-lockfile --prefer-offline
#       - name: Install Docs
#         working-directory: docs/
#         run: pnpm install --frozen-lockfile --prefer-offline
#       - name: Build Docs
#         working-directory: docs/
#         run: pnpm build
