name: Compile with typescript v4

on:
  push:
    branches: main
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  compile_with_typescript_v4:
    name: Compile with typescript v4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install typescript v4 in all packages
        run: |
          sed -i 's/"typescript": "~5.0.0"/"typescript": "^4.0.0"/' package.json packages/*/package.json && pnpm install
      # hardhat-viem is the only package that requires TypeScript v5
      - name: Remove hardhat-viem directory
        run: rm -fr packages/hardhat-viem
      - name: Remove hardhat-viem from the build script
        run: sed -i 's/packages\/hardhat-viem packages\/hardhat-toolbox-viem//' package.json
      - name: Build
        run: pnpm build
