name: Deploy after Hardhat release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.release.tag_name, 'hardhat.3')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_AFTER_HARDHAT_RELEASE_WEBHOOK }}"
      - name: Notify failures
        if: failure()
        uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
        with:
          payload: |
            {
              "workflow_name": "${{ github.workflow }}",
              "run_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.GH_ACTION_NOTIFICATIONS_SLACK_WEBHOOK_URL }}
