name: hardhat-truffle4 CI

on:
  push:
    branches: [$default-branch]
    paths:
      - "packages/hardhat-truffle4/**"
      - "packages/hardhat-web3-legacy/**"
      - "packages/hardhat-core/**"
      - "packages/hardhat-common/**"
      - "config/**"
  pull_request:
    branches:
      - "*"
    paths:
      - "packages/hardhat-truffle4/**"
      - "packages/hardhat-web3-legacy/**"
      - "packages/hardhat-core/**"
      - "packages/hardhat-common/**"
      - "config/**"

defaults:
  run:
    working-directory: packages/hardhat-truffle4

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test_on_windows:
    name: Test hardhat-truffle4 on Windows with Node 12
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test

  test_on_macos:
    name: Test hardhat-truffle4 on MacOS with Node 12
    runs-on: macos-latest
    # disable until actions/virtual-environments#4896 is fixed
    if: ${{ false }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test

  test_on_linux:
    name: Test hardhat-truffle4 on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16, 18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test
