name: Hardhat Network Tracing Capabilities, scheduled runs for all solc versions

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/hardhat-core

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test_tracing:
    name: Test tracing capabilities on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build
        run: pnpm build
      - name: Cache artifacts
        uses: actions/cache@v4
        with:
          path: |
            packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/artifacts
          key: hardhat-network-stack-traces-tests-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/**/*.sol') }}-${{ hashFiles('packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/**/test.json') }}-${{ hashFiles('packages/hardhat-core/test/internal/hardhat-network/stack-traces/**/*.ts') }}
      - name: Run tests
        env:
          DO_NOT_SET_THIS_ENV_VAR____IS_HARDHAT_CI: true
          FORCE_COLOR: 3
          NODE_OPTIONS: "--max-old-space-size=4096"
          HARDHAT_TESTS_ALL_SOLC_VERSIONS: true
        run: pnpm test:tracing
