name: hardhat-toolbox CI

on:
  push:
    branches: [$default-branch]
    paths:
      - "packages/hardhat-toolbox/**"
      - "packages/hardhat-core/**"
      - "packages/hardhat-chai-matchers/**"
      - "packages/hardhat-network-helpers/**"
      - "packages/hardhat-ethers/**"
      - "packages/hardhat-verify/**"
      - "packages/hardhat-common/**"
      - "config/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "packages/hardhat-toolbox/**"
      - "packages/hardhat-core/**"
      - "packages/hardhat-chai-matchers/**"
      - "packages/hardhat-network-helpers/**"
      - "packages/hardhat-ethers/**"
      - "packages/hardhat-verify/**"
      - "packages/hardhat-common/**"
      - "config/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/hardhat-toolbox

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test_on_windows:
    name: Test hardhat-toolbox on Windows with Node 18
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test

  test_on_macos:
    name: Test hardhat-toolbox on MacOS with Node 18
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test

  test_on_linux:
    name: Test hardhat-toolbox on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test
