name: Hardhat Network Tracing Capabilities CI

on:
  push:
    branches: [$default-branch]
    paths:
      - "packages/hardhat-core/**"
      - "packages/hardhat-common/**"
      - "config/**"
  pull_request:
    branches:
      - "*"
    paths:
      - "packages/hardhat-core/**"
      - "packages/hardhat-common/**"
      - "config/**"

defaults:
  run:
    working-directory: packages/hardhat-core

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test_tracing:
    name: Test tracing capabilities on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16, 18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Cache artifacts
        uses: actions/cache@v2
        with:
          path: |
            packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/**/artifacts
          key: hardhat-network-stack-traces-tests-${{ hashFiles('yarn.lock') }}-${{ hashFiles('packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/**/*.sol') }}-${{ hashFiles('packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/**/test.json') }}-${{ hashFiles('packages/hardhat-core/test/internal/hardhat-network/stack-traces/**/*.ts') }}
      - name: Run tests
        env:
          DO_NOT_SET_THIS_ENV_VAR____IS_HARDHAT_CI: true
          FORCE_COLOR: 3
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: yarn test:tracing
