name: hardhat-verify CI

on:
  push:
    branches: [$default-branch]
    paths:
      - "packages/hardhat-verify/**"
      - "packages/hardhat-core/**"
      - "packages/hardhat-common/**"
      - "config/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "packages/hardhat-verify/**"
      - "packages/hardhat-core/**"
      - "packages/hardhat-common/**"
      - "config/**"

defaults:
  run:
    working-directory: packages/hardhat-verify

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test_on_windows:
    name: Test hardhat-verify on Windows with Node 16
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test

  test_on_macos:
    name: Test hardhat-verify on MacOS with Node 16
    runs-on: macos-latest
    # disable until actions/virtual-environments#4896 is fixed
    if: ${{ false }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test

  test_on_linux:
    name: Test hardhat-verify on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test
