name: hardhat-chai-matchers CI

on:
  push:
    branches: [$default-branch]
    paths:
      - "packages/hardhat-chai-matchers/**"
      - "packages/hardhat-common/**"
      - "config/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "packages/hardhat-chai-matchers/**"
      - "packages/hardhat-common/**"
      - "config/**"

defaults:
  run:
    working-directory: packages/hardhat-chai-matchers

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test_on_windows:
    name: Test hardhat-chai-matchers on Windows with Node 18
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Run tests
        env:
          FORCE_COLOR: 3
        run: yarn test:ci
      - name: Cache downloaded compilers
        uses: actions/cache@v2
        with:
          path: |
            C:\Users\runneradmin\AppData\Local\hardhat-nodejs\Cache\compilers-v2
          key: downloaded-compilers-v2

  test_on_macos:
    name: Test hardhat-chai-matchers on MacOS with Node 18
    runs-on: macos-latest
    # disable until actions/virtual-environments#4896 is fixed
    # if: ${{ false }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Run tests
        env:
          FORCE_COLOR: 3
        run: yarn test:ci
      - name: Cache downloaded compilers
        uses: actions/cache@v2
        with:
          path: |
            /Users/runner/Library/Caches/hardhat-nodejs/compilers-v2
          key: downloaded-compilers-v2

  test_on_linux:
    name: Test hardhat-chai-matchers on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Run tests
        env:
          FORCE_COLOR: 3
        run: yarn test:ci
      - name: Cache downloaded compilers
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/.cache/hardhat-nodejs/compilers-v2
          key: downloaded-compilers-v2
