name: hardhat-ledger CI

on:
  push:
    branches:
      - main
    paths:
      - "packages/hardhat-ledger/**"
      - "packages/hardhat-core/**"
      - "packages/hardhat-common/**"
      - "config/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "packages/hardhat-ledger/**"
      - "packages/hardhat-core/**"
      - "packages/hardhat-common/**"
      - "config/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/hardhat-ledger

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test_on_windows:
    name: Test hardhat-ledger on Windows with Node 16
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install pnpm # pnpm is not insatlled by default in the CI
        run: npm install -g pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test

  test_on_macos:
    name: Test hardhat-ledger on MacOS with Node 16
    runs-on: macos-latest
    # disable until actions/virtual-environments#4896 is fixed
    if: ${{ false }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install pnpm # pnpm is not insatlled by default in the CI
        run: npm install -g pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test

  test_on_linux:
    name: Test hardhat-ledger on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm # pnpm is not insatlled by default in the CI
        run: npm install -g pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test
