name: Pre-release tests

on:
  push:
    branches: [pre-release-testing-branch]
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  pre_release_checks:
    name: Pre-release checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: lint
        run: yarn lint
      - name: Cache artifacts
        uses: actions/cache@v2
        with:
          path: |
            packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/artifacts
          key: hardhat-network-stack-traces-tests-${{ hashFiles('packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/**/*.sol') }}-${{ hashFiles('packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/**/test.json') }}-${{ hashFiles('packages/hardhat-core/test/internal/hardhat-network/stack-traces/**/*.ts') }}
      - name: test
        env:
          DO_NOT_SET_THIS_ENV_VAR____IS_HARDHAT_CI: true
          FORCE_COLOR: 3
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: yarn test
      - name: Check dependency versions
        run: node scripts/check-dependencies.js
  test_fork:
    name: Test Hardhat Network's forking functionality
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/hardhat-core
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Cache network requests
        uses: actions/cache@v2
        with:
          path: |
            packages/hardhat-core/test/internal/hardhat-network/provider/.hardhat_node_test_cache
          key: hardhat-network-forking-tests-${{ hashFiles('yarn.lock') }}-${{ hashFiles('packages/hardhat-core/test/internal/hardhat-network/provider/node.ts') }}
      - name: Run tests
        env:
          INFURA_URL: ${{ secrets.INFURA_URL }}
          ALCHEMY_URL: ${{ secrets.ALCHEMY_URL }}
          DO_NOT_SET_THIS_ENV_VAR____IS_HARDHAT_CI: true
          FORCE_COLOR: 3
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          yarn build
          yarn test:forking
